steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Initialize'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Initializing deployment for ${_DEPLOYMENT_NAME}"
      echo "Region: ${_REGION}"
      echo "Project: $PROJECT_ID"

- name: 'hashicorp/terraform:1.0.0'
  id: 'Terraform Init'
  args:
    - 'init'
    - '-backend=true'
    - '-backend-config=bucket=${_BUCKET_NAME}'
    - '-backend-config=prefix=${_DEPLOYMENT_NAME}/state'
  dir: 'deployments/doc-summarization'

- name: 'hashicorp/terraform:1.0.0'
  id: 'Terraform Plan'
  args:
    - 'plan'
    - '-var-file=terraform.tfvars'
    - '-out=tfplan'
  dir: 'deployments/doc-summarization'

- name: 'hashicorp/terraform:1.0.0'
  id: 'Terraform Apply'
  args:
    - 'apply'
    - '-auto-approve'
    - 'tfplan'
  dir: 'deployments/doc-summarization'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Verify Deployment'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Verifying deployment..."
      gcloud blueprints config show \
        --deployment=${_DEPLOYMENT_NAME} \
        --location=${_REGION} \
        --format="yaml"

timeout: '7200s'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

substitutions:
  _DEPLOYMENT_NAME: 'generative-ai-document-summarization'
  _REGION: 'us-central1'
  _BUCKET_NAME: '859242575175-us-central1-blueprint-config'
  _SOURCE_REF: 'sic-jss'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/terraform-sa-key/versions/latest
      env: 'GOOGLE_CREDENTIALS'

serviceAccount: 'goog-sc-generative-ai-docu-147@api-for-warp-drive.iam.gserviceaccount.com'
tags: ['gen-ai', 'doc-summarization', 'production']