steps:
  # Initialize with Authentication and Project Setup
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'initialize'
    args:
      - 'config'
      - 'set'
      - 'project'
      - 'api-for-warp-drive'
    env:
      - 'EMOTION_TUNING_PIPELINE=cloudbuild-ci-cttt-emotion-tuning.yaml'
      - 'EMOTION_TUNING_TRIGGER=emotion-tuning-cicd-trigger'

  # Basic Test Step
  - name: 'gcr.io/cloud-builders/npm'
    id: 'test'
    args: ['test']

timeout: '3600s' # 60 minutes
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'AGENT_ID=DR_CLAUDE_AUTOMATION'

artifacts:
  objects:
    location: 'gs://api-for-warp-drive-artifacts/builds/$BUILD_ID/'
    paths: ['test-results/**/*']

serviceAccount: 'drlucyautomation@api-for-warp-drive.iam.gserviceaccount.com'
