#!/bin/bash

# Direct deployment script for asoos.2100.cool
# This script sets up a direct deployment to the production server

echo "🚀 Starting direct deployment to asoos.2100.cool"

# Variables
DEPLOY_PACKAGE="/Users/as/asoos/aixtiv-cli/ui/asoos/asoos-2100-deploy-20250513054539.zip"
REMOTE_USER="your-username"  # Replace with your actual username
REMOTE_HOST="your-server-ip" # Replace with your actual server IP
SITE_ROOT="/var/www/asoos.2100.cool"
NGINX_CONF="/etc/nginx/sites-available/asoos.2100.cool"

# Verify package exists
if [ ! -f "$DEPLOY_PACKAGE" ]; then
  echo "❌ Deployment package not found: $DEPLOY_PACKAGE"
  exit 1
fi

echo "✅ Found deployment package: $DEPLOY_PACKAGE"

echo ""
echo "To complete the deployment, run the following commands:"
echo ""
echo "Step 1: Copy the deployment package to your server"
echo "scp $DEPLOY_PACKAGE $REMOTE_USER@$REMOTE_HOST:/tmp/"
echo ""
echo "Step 2: SSH into your server and extract the files"
echo "ssh $REMOTE_USER@$REMOTE_HOST"
echo ""
echo "Step 3: Once logged in to the server, run:"
echo "sudo mkdir -p $SITE_ROOT"
echo "sudo unzip /tmp/$(basename $DEPLOY_PACKAGE) -d $SITE_ROOT"
echo ""
echo "Step 4: Set up Nginx configuration"
echo "sudo bash -c 'cat > $NGINX_CONF << EOF"
echo "server {"
echo "    listen 80;"
echo "    server_name asoos.2100.cool;"
echo "    "
echo "    # Redirect HTTP to HTTPS"
echo "    return 301 https://\$host\$request_uri;"
echo "}"
echo ""
echo "server {"
echo "    listen 443 ssl;"
echo "    server_name asoos.2100.cool;"
echo "    "
echo "    ssl_certificate /etc/letsencrypt/live/asoos.2100.cool/fullchain.pem;"
echo "    ssl_certificate_key /etc/letsencrypt/live/asoos.2100.cool/privkey.pem;"
echo "    "
echo "    # Modern SSL config"
echo "    ssl_protocols TLSv1.2 TLSv1.3;"
echo "    ssl_prefer_server_ciphers off;"
echo "    "
echo "    root $SITE_ROOT/public;"
echo "    index index.html;"
echo "    "
echo "    # API proxy to backend"
echo "    location /api/ {"
echo "        proxy_pass http://localhost:3002/api/;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "    }"
echo "    "
echo "    # Static content caching"
echo "    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg)\$ {"
echo "        expires 30d;"
echo "        add_header Cache-Control \"public, max-age=2592000\";"
echo "    }"
echo "    "
echo "    # Service worker should not be cached"
echo "    location = /sw.js {"
echo "        expires -1;"
echo "        add_header Cache-Control \"no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0\";"
echo "    }"
echo "    "
echo "    # Handle SPA routing"
echo "    location / {"
echo "        try_files \$uri \$uri/ /index.html;"
echo "    }"
echo "}"
echo "EOF'"
echo ""
echo "Step 5: Enable the site and restart Nginx"
echo "sudo ln -sf $NGINX_CONF /etc/nginx/sites-enabled/"
echo "sudo nginx -t"
echo "sudo systemctl restart nginx"
echo ""
echo "Step 6: Set up Node.js service for the API backend"
echo "sudo bash -c 'cat > /etc/systemd/system/asoos-api.service << EOF"
echo "[Unit]"
echo "Description=ASOOS API Server"
echo "After=network.target"
echo ""
echo "[Service]"
echo "User=www-data"
echo "WorkingDirectory=$SITE_ROOT"
echo "ExecStart=/usr/bin/node server.js"
echo "Restart=always"
echo "RestartSec=10"
echo "StandardOutput=syslog"
echo "StandardError=syslog"
echo "SyslogIdentifier=asoos-api"
echo "Environment=NODE_ENV=production PORT=3002"
echo ""
echo "[Install]"
echo "WantedBy=multi-user.target"
echo "EOF'"
echo ""
echo "Step 7: Start the API service"
echo "sudo systemctl daemon-reload"
echo "sudo systemctl enable asoos-api"
echo "sudo systemctl start asoos-api"
echo ""
echo "Step 8: Verify deployment"
echo "sudo systemctl status asoos-api"
echo "curl -I https://asoos.2100.cool"
echo ""
echo "🎉 Deployment instructions complete!"